server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bdd_portal
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    cache: false
    mode: HTML

bdd:
  portal:
    features-path: ${BDD_PORTAL_FEATURES_PATH:src/test/resources/features}
    reports-path: target/allure-results
    selenium-grid-url: ${GRID_URL:http://141.94.137.133:5503/wd/hub}
    screenshots-path: bdd-reports/screenshots

logging:
  level:
    com.bdd.portal: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

test:
  environment: dev